### ISSUE TITLE
iron-collapsed paper-cards lose elevation property

### ISSUE THREAD

**Issue by Typel** [PolymerElements/iron-collapse#38]
Enclosing a paper-card element which has its elevation property set to one of {0|1|2|3|4|5} inside of an iron-collapse results in the paper-card element losing its elevation property (effectively, elevation="0")

I tested the same with paper-material and in this case, the elevation was preserved.

**Comment by valdrinkoshi** [comment]
Hi @Typel, `iron-collapse` has to set `overflow: auto` so that its contents are not rendered outside its bounds (that's the whole purpose of `iron-collapse` after all :) ).
In this example I could see that `elevation` is correctly preserved http://jsbin.com/keqajog/1/edit?html,output

`elevation` requires margin around it to be rendered without cropping; as per the [documentation](https://elements.polymer-project.org/elements/iron-collapse):
> iron-collapse adjusts the height/width of the collapsible element to show/hide the content. So avoid putting padding/margin/border on the collapsible directly, and instead put a div inside and style that.

**Comment by Typel** [comment]
My apologies, you are correct. I can see now that my test cases were flawed - thanks so much for the explanation.

**Comment by valdrinkoshi** [comment]
No problem! Anyways, thinking of this a bit more, I think it should be safe for `iron-collapse` to set `overflow: visible` when it is opened..! I'll reopen this issue and do a PR with a fix for this
