### ISSUE TITLE
iron-collapse not behaving right inside iron-list

### ISSUE THREAD

**Issue by Skeec** [PolymerElements/iron-collapse#69]
### Description

The `iron-collapse` element doesn't `notifyResize()` appropriately inside of `iron-list`.
### Expected outcome

Resizing as the animations plays out.
### Actual outcome & Live Demo

Here's how it currently behaves: http://jsbin.com/vaqatawale/1/edit?html,output
### Steps to reproduce
1. Put a `iron-collapse` element in the page sourrounded by `iron-list` element.
2. Make sure the `iron-collapse` element is animated - doesn't have `no-animation` attribute set.
3. Open the page in a web browser.
4. Trigger the animation.
### Browsers Affected

- [X] Chrome
- [X] Firefox
- [X] Safari 9
- [X] Safari 8
- [X] Safari 7
- [X] Edge
- [X] IE 11
- [X] IE 10

**Comment by valdrinkoshi** [comment]
Hi @Skeec, actually this happens because of the way `iron-list` virtualizes the rendered rows. @blasten can give more details, but in a nutshell `iron-list` positions absolutely each row and positions it with `transform` to optimize in performance and avoid expensive layouts. As a consequence, elements animating within a row won't affect the row size until you notify about it.
A (very poor performing) solution would be to fire `iron-resize` at each `requestAnimationFrame` until the animation's over...

**Comment by Skeec** [comment]
Can't I hook into the transformation itself and say fire `iron-resize`?

**Comment by valdrinkoshi** [comment]
unfortunately there is not much that can be done by `iron-collapse` itself.
I've experimented a bit with an element that assumes to be used inside an `<iron-list>`, and hence updates the position of its siblings while animating. Check it out here https://github.com/PolymerLabs/show-more

Will close this issue as I don't see action items for iron-collapse
